In [1]:
#setup
# Python ≥3.5 is required
import sys
assert sys.version_info >= (3, 5)

# Is this notebook running on Colab or Kaggle?
IS_COLAB = "google.colab" in sys.modules
IS_KAGGLE = "kaggle_secrets" in sys.modules

# Scikit-Learn ≥0.20 is required
import sklearn
assert sklearn.__version__ >= "0.20"

# Common imports
import numpy as np
import os

# to make this notebook's output stable across runs
np.random.seed(42)

# To plot pretty figures
%matplotlib inline
import matplotlib as mpl
import matplotlib.pyplot as plt
mpl.rc('axes', labelsize=14)
mpl.rc('xtick', labelsize=12)
mpl.rc('ytick', labelsize=12)

# Where to save the figures
PROJECT_ROOT_DIR = "."
CHAPTER_ID = "classification"
IMAGES_PATH = os.path.join(PROJECT_ROOT_DIR, "images", CHAPTER_ID)
os.makedirs(IMAGES_PATH, exist_ok=True)

def save_fig(fig_id, tight_layout=True, fig_extension="png", resolution=300):
    path = os.path.join(IMAGES_PATH, fig_id + "." + fig_extension)
    print("Saving figure", fig_id)
    if tight_layout:
        plt.tight_layout()
    plt.savefig(path, format=fig_extension, dpi=resolution)

In [5]:
import numpy as np
x = 2 * np.random.rand(100, 1)
y = 4  + 3 * x + np.random.randn(100, 1)


In [6]:
x

array([[1.58962261],
       [1.00527419],
       [1.15380777],
       [0.98503539],
       [0.39048598],
       [1.44490423],
       [0.56154472],
       [0.04863193],
       [1.29094459],
       [0.35422136],
       [1.88091717],
       [1.90785715],
       [1.82972878],
       [0.7403174 ],
       [0.03091323],
       [1.85663713],
       [0.8563683 ],
       [1.93330964],
       [1.92723995],
       [1.70601891],
       [0.58889778],
       [0.77019546],
       [1.70227334],
       [0.63384401],
       [0.33898549],
       [1.11360252],
       [1.87230955],
       [1.39205959],
       [1.14012234],
       [0.19435299],
       [1.23001445],
       [1.9801077 ],
       [0.28016803],
       [1.0366593 ],
       [1.75474614],
       [1.48153724],
       [1.39403148],
       [1.40496817],
       [0.7189823 ],
       [0.58718369],
       [1.61872231],
       [1.62022679],
       [1.73414464],
       [1.82648111],
       [1.0226848 ],
       [1.00303259],
       [1.59659036],
       [1.299

In [7]:
y

array([[10.03577897],
       [ 6.30815309],
       [ 7.90524274],
       [ 7.72974022],
       [ 4.24452746],
       [ 8.27518734],
       [ 2.44336683],
       [ 3.12150816],
       [ 7.62026562],
       [ 3.81488089],
       [11.27516281],
       [ 8.29343008],
       [ 9.04914185],
       [ 6.35169278],
       [ 5.53401299],
       [ 8.13404922],
       [ 7.73226864],
       [ 9.81016198],
       [ 8.80021121],
       [ 9.58016021],
       [ 5.96575305],
       [ 5.71036949],
       [ 9.17662211],
       [ 5.51621843],
       [ 5.13047383],
       [ 8.00293825],
       [11.20294546],
       [ 6.93836328],
       [ 9.5534004 ],
       [ 2.63097116],
       [ 7.53825827],
       [10.52864031],
       [ 5.12149596],
       [ 6.48727839],
       [ 9.05611618],
       [ 7.95161077],
       [ 7.59272969],
       [ 9.0645066 ],
       [ 6.51396239],
       [ 5.06864147],
       [ 9.75576681],
       [ 9.16797989],
       [10.01529603],
       [10.10907216],
       [ 6.23905938],
       [ 6

In [8]:
x_b = np.c_[np.ones((100, 1)), x]
theta_best = np.linalg.inv(x_b.T.dot(x_b)).dot(x_b.T).dot(y)

In [9]:
x_b

array([[1.        , 1.58962261],
       [1.        , 1.00527419],
       [1.        , 1.15380777],
       [1.        , 0.98503539],
       [1.        , 0.39048598],
       [1.        , 1.44490423],
       [1.        , 0.56154472],
       [1.        , 0.04863193],
       [1.        , 1.29094459],
       [1.        , 0.35422136],
       [1.        , 1.88091717],
       [1.        , 1.90785715],
       [1.        , 1.82972878],
       [1.        , 0.7403174 ],
       [1.        , 0.03091323],
       [1.        , 1.85663713],
       [1.        , 0.8563683 ],
       [1.        , 1.93330964],
       [1.        , 1.92723995],
       [1.        , 1.70601891],
       [1.        , 0.58889778],
       [1.        , 0.77019546],
       [1.        , 1.70227334],
       [1.        , 0.63384401],
       [1.        , 0.33898549],
       [1.        , 1.11360252],
       [1.        , 1.87230955],
       [1.        , 1.39205959],
       [1.        , 1.14012234],
       [1.        , 0.19435299],
       [1.

In [10]:
theta_best

array([[3.86501051],
       [3.13916179]])

'5'